services:
  web:
    build: .

    ports:
      - 8000:8000
#    depends_on:
#      - db
    environment:
      DJANGO_SECRET_KEY: "django-insecure-_-4sm^2^=abgv(p3=_v)an_xn5!=^byx%1b7d8zrd1)50mt7yb"
      DJANGO_DEBUG: "True"
      DJANGO_SECURE_SSL_REDIRECT: "False"

      DJANGO_SECURE_HSTS_SECONDS: "0"
      DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS: "False"
      DJANGO_SECURE_HSTS_PRELOAD: "False"

      DJANGO_SESSION_COOKIE_SECURE: "False"
      DJANGO_CSRF_COOKIE_SECURE: "False"

      POSTGRES_DB_NAME: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"

  db:
    image: postgres:17
    environment:
      POSTGRES_DB_NAME: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data: